[package]
name = "texlight"
version = "0.0.0"
description = "pdf-LaTeX superset language-server wrapper thingy"
authors = ["jonas-kell"]
license = "MIT"
repository = "https://github.com/jonas-kell/texlight"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"


