services:
    main-service:
        build:
            context: ./
            dockerfile: ./docker/dev/Dockerfile
        # ports:
        #    - "8080:8080"
        volumes:
            - rust_build_cache:/usr/local/cargo/registry/
            - ./:/app/
        environment:
            - RUST_LOG=debug
        command: cargo watch -x "run dev"

    compile-wasm:
        build:
            context: ./
            dockerfile: ./docker/dev/Dockerfile
        volumes:
            - rust_build_cache:/usr/local/cargo/registry/
            - ./:/app/
        command: wasm-pack build --target web
        profiles:
            - extra_compile_task

volumes:
    rust_build_cache:
